name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: '50'

      - name: Print PRs
        run: gh pr list --state open

      - name: Run The Pull Request Merger
        uses: agorararmard/pull-request-merger-action@main

