name: Pull Request Internal Merger

on:
  #schedule:
  #  - cron: '*/1 * * * *'
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: '50'

      - name: Run The Pull Request Merger
        uses: agorararmard/pull-request-merger-action@main


